# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        MosparoRpg\Type\TypeInterface:
            tags: [ 'mosparoRpg.type' ]

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    MosparoRpg\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    MosparoRpg\Processor\:
        resource: '../src/Processor'
        public: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    MosparoRpg\Type\Manager:
        class: MosparoRpg\Type\Manager
        arguments: [ !tagged mosparoRpg.type ]

    MosparoRpg\Processor\MainProcessor:
        class: MosparoRpg\Processor\MainProcessor
        arguments:
            - '@service_container'

    MosparoRpg\Helper\UuidHelper:
        class: MosparoRpg\Helper\UuidHelper
